spring.application.name=orbitalert

# Oracle ? lê variáveis de ambiente no Render, usa valores fixos como fallback local
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:rm563719}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:111206}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cache
spring.cache.type=simple

# Swagger
springdoc.swagger-ui.path=/swagger